### PR TITLE
#102 Update chat-portrait-style-pf2e.css

### LINKED ISSUE #102: PF2e justify-content Styling
With the new 0.7.0 update, a lot of systems got their custom CSS sheets, at least from my brief look at the git history.
With the update came the following styling:
```
.message .chat-portrait-message-header-pf2e .message-metadata {
  flex: 0 0 auto;
  margin-left: 1rem;
}
```
The `flex: 0 0 auto;` resulting in names in chat messages to look like this

image

Chrome's Breakdown of it:

image

Such styling came out of nowhere and it would be nice to be able to, at the very least, toggle it off. I very much liked having names to to the left and the details and buttons to the right, and with modules such as Illandril's Chat Enhancements, it only gets worse.

image

### PR DESCRIPTION
**Pull request by MrVauxs**
Fixes #102, duplicate this change to every other CSS file if others want the same old left-adjustment

### CODE REVIEW

**Comment by p4535992** [comment]
thanks I had already seen your ticket, but I thank you even more for the pr if I can integrate it tonight or tomorrow night at the latest.

**Comment by MrVauxs** [comment]
Pushed a new update due to the following: 
image

Now fixed to
image

Still have to figure out what causes the modifiers to go to the right.

**Comment by MrVauxs** [comment]
For some strange reason the "Display Chat Message for ROLL" setting modifies the HTML as shown (up is off, down is on):
image
image

**Comment by MrVauxs** [comment]
After looking over the CSS changes, I am leaving this open rather than try to create and submit a true fix, as I'm most likely not going to do so.
Short of deleting the entire CSS, staying at 0.6.4 is a much easier solution to the problems I had in my games because of 0.7.X than trying to scrounge up what's going wrong in the CSS files.

**Comment by p4535992** [comment]
@MrVauxs can't replicate, but try out 0.7.2 and let me know it

**Pull request merged**
