### PR TITLE
Upgrade of the project in preparation of FoundryVTT 0.8.0

### PR DESCRIPTION
**Pull request by p4535992**
- Preparation for foundry 0.8.0
- Bootstrapped with League of Extraordinary FoundryVTT Developers  [foundry-vtt-types](https://github.com/League-of-Foundry-Developers/foundry-vtt-types)
- Added [Bug Reporter Module](https://foundryvtt.com/packages/bug-reporter/)
- [New Feature: Configurable option to use the player's color as blended background color of the message. by @Biggles](https://github.com/MOAM-Biggles/FoundryVTT-Chat-Portrait/) 
- [Translation: Updated German translation by @Biggles](https://github.com/MOAM-Biggles/FoundryVTT-Chat-Portrait/) 
- [Added option to use player's color as blended background color of the](https://github.com/MOAM-Biggles/FoundryVTT-Chat-Portrait/commit/420f018bdcb5a37cf0e5e3ad5a61e6dccc318abd)

### CODE REVIEW

**Comment by vlaminck** [comment]
@ShoyuVanilla, is there a timeline for merging this or have you abandoned this project? @p4535992 seems to be pretty active, and I'm wondering if we should all use that fork instead.

**Comment by jbblily** [comment]
Hello, I asked ShoyuVanilla about this module and he said he is too busy to maintain this project. 
He said it is free to fork this and make another project, so I think it is better to use this fork instead.

**Comment by vlaminck** [comment]
That makes sense, thanks @jbblily 

@p4535992, You seem pretty active, would you be willing to take over as the maintainer of this project?

**Comment by p4535992** [comment]
I will try to contact  ShoyuVanilla and make me contributor of his  project, i don't want to create a new module (there are to many already).

**Comment by p4535992** [comment]
In the meantime I am waiting for ShoyuVanilla to answer me I have modified the module.json of my fork to make it manually installable

**Pull request merged**
